Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.provider "hyperv"

  config.vm.provision :shell, path: "scripts/install_chrome.ps1"
  config.vm.provision "file", source: "C:/Users/Arto/Documents/hogent/3_1/projecten/box/scripts/configure_ip.ps1", destination: "C:/Users/vagrant/Desktop/script.ps1"

#  config.vm.provision :shell, path: "scripts/keyboard.ps1"
#  config.vm.provision :shell, path: "scripts/restart.cmd"

  config.vm.provider "hyperv" do |h|
     h.vmname = "Oscar2_MonitoringServer"
     h.memory = "2048"
  end

end
